export const mockData = [
    {
      task: "Task Heading",
      description: "organizations to provide access to education...",
      statusLabel: "Late",
      dueDate: "31 Mar 2025",
      progress: 20,
      owner: "Pushpa",
      ownerRole: "Manager",
      priority: "Medium",
      comments: "01",
      subTaskIcon: "add", // plus icon
    },
    {
      task: "Task Heading",
      description: "organizations to provide access to education...",
      statusLabel: "Late",
      dueDate: "31 Mar 2025",
      progress: 20,
      owner: "Pushpa",
      ownerRole: "Manager",
      priority: "High",
      comments: "01",
      subTaskIcon: "add",
    },
    {
      task: "Task Heading",
      description: "organizations to provide access to education...",
      statusLabel: "Late",
      dueDate: "31 Mar 2025",
      progress: 20,
      owner: "Pushpa",
      ownerRole: "Manager",
      priority: "Low",
      comments: "01",
      subTaskIcon: "add",
    },
    {
      task: "Task Heading",
      description: "organizations to provide access to education...",
      statusLabel: "Late",
      dueDate: "31 Mar 2025",
      progress: 20,
      owner: "Pushpa",
      ownerRole: "Manager",
      priority: "Medium",
      comments: "01",
      subTaskIcon: "add",
    },
    {
      task: "Task Heading",
      description: "organizations to provide access to education...",
      statusLabel: "Late",
      dueDate: "31 Mar 2025",
      progress: 20,
      owner: "Pushpa",
      ownerRole: "Manager",
      priority: "Medium",
      comments: "01",
      subTaskIcon: "add",
    },
    {
      task: "Task Heading",
      description: "organizations to provide access to education...",
      statusLabel: "Late",
      dueDate: "31 Mar 2025",
      progress: 20,
      owner: "Pushpa",
      ownerRole: "Manager",
      priority: "Medium",
      comments: "01",
      subTaskIcon: "add",
    },
    {
      task: "Task Heading",
      description: "organizations to provide access to education...",
      statusLabel: "Late",
      dueDate: "31 Mar 2025",
      progress: 20,
      owner: "Pushpa",
      ownerRole: "Manager",
      priority: "Medium",
      comments: "01",
      subTaskIcon: "add",
    },
    {
      task: "Task Heading",
      description: "organizations to provide access to education...",
      statusLabel: "Late",
      dueDate: "31 Mar 2025",
      progress: 20,
      owner: "Pushpa",
      ownerRole: "Manager",
      priority: "Medium",
      comments: "01",
      subTaskIcon: "add",
    },
    {
      task: "Task Heading",
      description: "organizations to provide access to education...",
      statusLabel: "Late",
      dueDate: "31 Mar 2025",
      progress: 20,
      owner: "Pushpa",
      ownerRole: "Manager",
      priority: "Medium",
      comments: "01",
      subTaskIcon: "add",
    },
    {
      task: "Task Heading",
      description: "organizations to provide access to education...",
      statusLabel: "Late",
      dueDate: "31 Mar 2025",
      progress: 20,
      owner: "Pushpa",
      ownerRole: "Manager",
      priority: "Medium",
      comments: "01",
      subTaskIcon: "add",
    },
  ];
  