export const mockData = [
    {
        id:"1",
        task: "Objective",
      description: "Expand educational opportunities to underprivileged communities through partnerships.",
      statusLabel: "Late",
      dueDate: "31 Mar 2025",
      progress: 20,
      owner: "Pushpa",
      ownerRole: "Manager",
      status: "Draft",

      subTaskIcon: "add",
      weight:"50%"
    },
    {
        id:"2",
        task: "Objective",
      description: "Support farmers with sustainable techniques and market access to improve incomes.",
      statusLabel: "Late",
      dueDate: "31 Mar 2025",
      progress: 20,
      owner: "Pushpa",
      ownerRole: "Manager",
      status: "Submit",

      subTaskIcon: "edit",
      weight:"50%",
    },
    {
        id:"3",
        task: "Objective",
      description: "Placeholder project description for internal documentation testing.",
      statusLabel: "Late",
      dueDate: "31 Mar 2025",
      progress: 20,
      owner: "Pushpa",
      ownerRole: "Manager",
      status: "Submit",
      
      subTaskIcon: "edit",
      weight:"50%",
    },
    {
        id:"4",
        task: "Objective",
      description: "Launch new scholarship initiatives across rural areas to boost literacy rates.",
      statusLabel: "Late",
      dueDate: "31 Mar 2025",
      progress: 20,
      owner: "Pushpa",
      ownerRole: "Manager",
      status: "Draft",
      
      subTaskIcon: "add",

      weight:"50%",
    },
    {
        id:"5",
        task: "Objective",
      description: "Develop digital learning programs for remote regions lacking internet access.",
      statusLabel: "Late",
      dueDate: "31 Mar 2025",
      progress: 20,
      owner: "Pushpa",
      ownerRole: "Manager",
      status: "Draft",
      
      subTaskIcon: "add",
      weight:"50%",
    },
    {
        id:"6",
        task: "Objective",
      description: "Partner with NGOs to train teachers in advanced teaching methodologies.",
      statusLabel: "Late",
      dueDate: "31 Mar 2025",
      progress: 20,
      owner: "Pushpa",
      ownerRole: "Manager",
      status: "Draft",
      
      subTaskIcon: "add",
      weight:"50%",
    },
    {
        id:"7",
        task: "Objective",
      description: "Implement mobile classrooms to reach nomadic and rural populations.",
      statusLabel: "Late",
      dueDate: "31 Mar 2025",
      progress: 20,
      owner: "Pushpa",
      ownerRole: "Manager",
      status: "Draft",
      
      subTaskIcon: "add",
      weight:"50%",
    },
    {
        id:"8",
        task: "Objective",
      description: "Launch awareness campaigns to promote girls' education in remote areas.",
      statusLabel: "Late",
      dueDate: "31 Mar 2025",
      progress: 20,
      owner: "Pushpa",
      ownerRole: "Manager",
      status: "Draft",
     
      subTaskIcon: "add",
      weight:"50%",
    },
    {
        id:"9",
        task: "Objective",
      description: "Create learning modules for skill development among youth in villages.",
      statusLabel: "Late",
      dueDate: "31 Mar 2025",
      progress: 20,
      owner: "Pushpa",
      ownerRole: "Manager",
      status: "Draft",
      
      subTaskIcon: "add",
      weight:"50%",
    },
    {
        id:"10",
        task: "Objective",
      description: "Set up low-cost education centers with support from corporate sponsors.",
      statusLabel: "Late",
      dueDate: "31 Mar 2025",
      progress: 20,
      owner: "Pushpa",
      ownerRole: "Manager",
      status: "Draft",
      
      subTaskIcon: "add",
      weight:"50%",
    },
  ];
  