export const mockData = [
    {
        id:"1",
      task: "Improve Livelihoods through Sustainable Livestock Farming",
      description: "",
      statusLabel: "Late",
      dueDate: "31 Mar 2025",
      progress: 20,
      owner: "Pushpa",
      ownerRole: "Manager",
      priority: "Medium",
      comments: "01",
      subTaskIcon: "add", // plus icon
      subTask:
       [
        {
        id:"1",
        task: "Improve Livelihoods through Sustainable Livestock Farming",
        description: "",
        statusLabel: "Late",
        dueDate: "31 Mar 2025",
        progress: 20,
        owner: "Pushpa",
        ownerRole: "Manager",
        priority: "Medium",
        comments: "01",
        subTaskIcon: "add", // plus icon
        },
        {
        id:"12",
        task: "Improve Livelihoods through Sustainable Livestock Farming",
        description: "",
        statusLabel: "Late",
        dueDate: "31 Mar 2025",
        progress: 20,
        owner: "Pushpa",
        ownerRole: "Manager",
        priority: "Medium",
        comments: "01",
        subTaskIcon: "add", // plus icon
        },

       ]

      
      
    },
    {
        id:"2",
      task: "Lorem Ipsum Dolar...",
      description: "",
      statusLabel: "Late",
      dueDate: "31 Mar 2025",
      progress: 20,
      owner: "Pushpa",
      ownerRole: "Manager",
      priority: "Medium",
      comments: "01",
      subTaskIcon: "edit", // pencil icon
    },
    {
        id:"3",
      task: "Improve Livelihoods through Sustainable Livestock Farming",
      description: "",
      statusLabel: "Late",
      dueDate: "31 Mar 2025",
      progress: 20,
      owner: "Pushpa",
      ownerRole: "Manager",
      priority: "Medium",
      comments: "01",
      subTaskIcon: "add",
    },
    {
        id:"4",
      task: "Improve Livelihoods through Sustainable Livestock Farming",
      description: "",
      statusLabel: "Late",
      dueDate: "31 Mar 2025",
      progress: 20,
      owner: "Pushpa",
      ownerRole: "Manager",
      priority: "High",
      comments: "01",
      subTaskIcon: "add",
    },
    {
        id:"5",

      task: "Improve Livelihoods through Sustainable Livestock Farming",
      description: "",
      statusLabel: "Late",
      dueDate: "31 Mar 2025",
      progress: 20,
      owner: "Pushpa",
      ownerRole: "Manager",
      priority: "Medium",
      comments: "01",
      subTaskIcon: "add",
    },
    {
        id:"6",

      task: "Improve Livelihoods through Sustainable Livestock Farming",
      description: "",
      statusLabel: "Late",
      dueDate: "31 Mar 2025",
      progress: 20,
      owner: "Pushpa",
      ownerRole: "Manager",
      priority: "Medium",
      comments: "01",
      subTaskIcon: "add",
    },
    {
        id:"7",

      task: "Improve Livelihoods through Sustainable Livestock Farming",
      description: "",
      statusLabel: "Late",
      dueDate: "31 Mar 2025",
      progress: 20,
      owner: "Pushpa",
      ownerRole: "Manager",
      priority: "Medium",
      comments: "01",
      subTaskIcon: "add",
    },
    {
        id:"8",

      task: "Improve Livelihoods through Sustainable Livestock Farming",
      description: "",
      statusLabel: "Late",
      dueDate: "31 Mar 2025",
      progress: 20,
      owner: "Pushpa",
      ownerRole: "Manager",
      priority: "Medium",
      comments: "01",
      subTaskIcon: "add",
    },
    {
        id:"9",

      task: "Improve Livelihoods through Sustainable Livestock Farming",
      description: "",
      statusLabel: "Late",
      dueDate: "31 Mar 2025",
      progress: 20,
      owner: "Pushpa",
      ownerRole: "Manager",
      priority: "Medium",
      comments: "01",
      subTaskIcon: "add",
    },
    {
        id:"10",

      task: "Improve Livelihoods through Sustainable Livestock Farming",
      description: "",
      statusLabel: "Late",
      dueDate: "31 Mar 2025",
      progress: 20,
      owner: "Pushpa",
      ownerRole: "Manager",
      priority: "Medium",
      comments: "01",
      subTaskIcon: "add",
    },
  ];