export const attendanceData = [
    {
      id: "1",
      day: "Sunday",
      dateString: "06 Apr 2025",
      timeIn: "00:00",
      timeOut: "16:44",
      hours: "7hr 13m",
      source: "Manual",
      action: "Add",
    },
    {
      id: "2",
      day: "Monday",
      dateString: "07 Apr 2025",
      timeIn: "09:00",
      timeOut: "16:44",
      hours: "7hr 13m",
      source: "Biometric",
      action: "Add",
    },
    {
      id: "3",
      day: "Tuesday",
      dateString: "08 Apr 2025",
      timeIn: "08:00",
      timeOut: "16:44",
      hours: "7hr 13m",
      source: "Manual",
      action: "Add",
    },
    {
      id: "4",
      day: "Wednesday",
      dateString: "09 Apr 2025",
      timeIn: "06:00",
      timeOut: "16:44",
      hours: "7hr 13m",
      source: "Biometric",
      action: "Add",
    },
    {
      id: "5",
      day: "Thursday",
      dateString: "10 Apr 2025",
      timeIn: "00:00",
      timeOut: "16:44",
      hours: "7hr 13m",
      source: "Manual",
      action: "Add",
    },
    {
      id: "6",
      day: "Friday",
      dateString: "11 Apr 2025",
      timeIn: "07:00",
      timeOut: "16:44",
      hours: "7hr 13m",
      source: "Biometric",
      action: "Add",
    },
    {
      id: "7",
      day: "Saturday",
      dateString: "12 Apr 2025",
      timeIn: "09:00",
      timeOut: "16:44",
      hours: "7hr 13m",
      source: "Manual",
      action: "Add",
    },
  ];
  